services:
  postgres:
    image: 'postgres:latest'
    environment:
      - 'POSTGRES_DB=redditdb'
      - 'POSTGRES_PASSWORD=Supersecret'
      - 'POSTGRES_USER=admin'
    ports:
      - "5432:5432"
    volumes:
      - 'postgres-data:/var/lib/postgresql/data'
volumes:
  postgres-data: