services:
  postgres:
    image: 'postgres:latest'
    environment:
      - 'POSTGRES_DB=redditdb'
      - 'POSTGRES_PASSWORD=password'
      - 'POSTGRES_USER=postgres'
    ports:
      - "5432:5432"
    volumes:
      - 'postgres-data:/var/lib/postgresql'
volumes:
  postgres-data: